<?xml version="1.0" encoding="utf-8"?><Database Name="TLT_Inventory" Class="DatabaseConnectionManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Coruscant;Initial Catalog=TLT_Inventory;Persist Security Info=True;User ID=tltinvfull" SettingsObjectName="TLTDatabaseEditor.Properties.Settings" SettingsPropertyName="TLT_InventoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Building" Member="Buildings">
    <Type Name="Building">
      <Column Name="BuildingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BuildingName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BuildingCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Classroom" Member="Classrooms">
    <Type Name="Classroom">
      <Column Name="RoomNumber" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuildingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClassroomFeatureDesc" Member="ClassroomFeatureDescs">
    <Type Name="ClassroomFeatureDesc">
      <Column Name="FeatureDescID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoomNumber" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuildingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FeatureDesc" Member="FeatureDescs">
    <Type Name="FeatureDesc">
      <Column Name="FeatureDescID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="BuildingQueries">
    <Type Name="BuildingQuery">
      <Column Name="BuildingID" Type="System.String" CanBeNull="false" />
      <Column Name="BuildingName" Type="System.String" CanBeNull="false" />
      <Column Name="BuildingCode" Type="System.String" CanBeNull="false" />
      <Column Name="Enabled" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="ClassroomQueries">
    <Type Name="ClassroomQuery">
      <Column Member="RoomNumber" Type="System.String" CanBeNull="false" />
      <Column Member="BuildingID" Type="System.String" CanBeNull="false" />
      <Column Member="Enabled" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="ClassroomFeatureDescQueries">
    <Type Name="ClassroomFeatureDescQuery">
      <Column Member="FeatureDescID" Type="System.String" CanBeNull="false" />
      <Column Member="RoomNumber" Type="System.String" CanBeNull="false" />
      <Column Member="BuildingID" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>